// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA555iNyvUCv3oJR1Q5zpS1ReknayBXt_U',
    appId: '1:431207330435:web:871cf18c6781b56594a1b6',
    messagingSenderId: '431207330435',
    projectId: 'momentashare',
    authDomain: 'momentashare.firebaseapp.com',
    storageBucket: 'momentashare.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgutb9PwAxi6WEKtJt1F8YD2nFCFBZ3ec',
    appId: '1:431207330435:android:2906f5d67512975094a1b6',
    messagingSenderId: '431207330435',
    projectId: 'momentashare',
    storageBucket: 'momentashare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjs-8M0N2JyevNgdXkNBye80l944ZeXmM',
    appId: '1:431207330435:ios:c3efac4551c3be0894a1b6',
    messagingSenderId: '431207330435',
    projectId: 'momentashare',
    storageBucket: 'momentashare.appspot.com',
    iosBundleId: 'com.example.momentaShare',
  );
}
